networks:
  lana:
    ipam:
      config:
        - subnet: 172.20.0.0/26
  lanb: 
    ipam:
      config:
        - subnet: 172.20.0.64/27
  lanc: 
    ipam:
      config:
        - subnet: 172.20.0.96/28
  r1_r2: 
    ipam:
      config:
        - subnet: 172.20.0.112/29
  r2_r3: 
    ipam:
      config:
        - subnet: 172.20.0.128/29
services:
  r1:
    image: arm64v8/ubuntu:22.04
    platform: linux/arm64
    container_name: r1
    privileged: true
    command: tail -f /dev/null
    networks:
      lana:
        ipv4_address: 172.20.0.2
      r1_r2:
        ipv4_address: 172.20.0.114
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./configs/r1:/etc/frr

  r2:
    image: arm64v8/ubuntu:22.04
    platform: linux/arm64
    container_name: r2
    privileged: true
    command: tail -f /dev/null
    networks:
      lanb:
        ipv4_address: 172.20.0.66
      r1_r2:
        ipv4_address: 172.20.0.115
      r2_r3:
        ipv4_address: 172.20.0.130
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./configs/r2:/etc/frr

  r3:
    image: arm64v8/ubuntu:22.04
    platform: linux/arm64
    container_name: r3
    privileged: true
    command: tail -f /dev/null
    networks:
      lanc:
        ipv4_address: 172.20.0.98
      r2_r3:
        ipv4_address: 172.20.0.131
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./configs/r3:/etc/frr

